### ISSUE TITLE
Ocarina of Time 1.0 NTSC intro

### ISSUE THREAD

**Issue by Alexn64gamer0712** [ata4/angrylion-rdp-plus#139] opened 2022-03-02 13:30 UTC
no "Nintendo 64" in the intro logo for this game, 1.0 version ntsc usa

![image](https://user-images.githubusercontent.com/100775660/156370805-869cc057-5639-4771-8bfd-d67f836918c0.png)
 
it works with GlideN64, Jabos plugin, and Porject64 default plugin

![image](https://user-images.githubusercontent.com/100775660/156371028-be379ae4-97e7-403a-a9a4-f3fa49ff5a38.png)

**Comment by flagrama** [comment] 2022-03-02 13:31
It works with all of the included plugins? So, what's the issue?

**Comment by GhostlyDark** [comment] 2022-03-02 19:12
Duplicate of #138

**Closed** 2022-03-12 22:18 UTC
