### ISSUE TITLE
Bugged lighting with Watt on Paper Mario

### ISSUE THREAD

**Issue by tomster785** [ata4/angrylion-rdp-plus#80] opened 2019-02-08 02:22 UTC
![watt bug pj64](https://user-images.githubusercontent.com/47438658/52455461-08653180-2b48-11e9-9dc8-86caea17bd87.png)

**Comment by RokkumanX** [comment] 2019-05-27 06:51
@tomster785 

Could you provide with a sram/fla save file near this location and specific event? I have no intention playing through Paper Mario all the way up to that specific point.

Unless there is few specific areas where there is darkness Watt can light up all the time but I highly doubt it.

**Comment by RokkumanX** [comment] 2019-05-31 19:47
Is there anyone out in the world that has a PAL save file at this location in the game or any location where Watt can light up a dark room?

I might be interested in replaying the game in a near future but only for this issue not so much.

Thanks in advance.

**Comment by ata4** [comment] 2019-05-31 19:52
I've played the game in the past and have some save games, so I might be able to locate a suitable location. It's been a while, though...

**Comment by zenseii** [comment] 2019-06-02 03:50
This type of illumination effect can be done in Shy Guy Toy Box and Lava Lava Island. I have some save games for the US version that I could provide in these exact locations. However, I think this problem is only present in Skelux' multiplayer mod. I'll provide saves later

**Comment by RokkumanX** [comment] 2019-06-02 05:49
Thanks, that means my completed save file is rather useless.

Also now that I think about it, I don't think US saves can be used on a PAL copy like I have.

I have tried using US saves numerous times and the result were always the same, no working saves.
Nintendo 64 games/saves have always been hit and miss ending up completing the games for myself.

**Comment by zenseii** [comment] 2019-06-03 11:50
[Paper Mario (U) Lighting Test.pj.zip](https://github.com/ata4/angrylion-rdp-plus/files/3247387/Paper.Mario.U.Lighting.Test.pj.zip)
[Paper Mario Multiplayer Lighting Test.pj.zip](https://github.com/ata4/angrylion-rdp-plus/files/3247388/Paper.Mario.Multiplayer.Lighting.Test.pj.zip)
Here are save states. To check if lighting works just go into the room to the left. Press C-Stick down to check if the room dims or lights up as it should. I attached a save state for the mod as well, but when I tested it now it worked fine though I first ran gliden64 with the emu. I checked with v97, though I could check with a more recent release as well.

**Comment by RokkumanX** [comment] 2019-06-05 10:53
Thanks @zenseii 

As a PAL owner of the game I'm sorry to say that I can't test this out, Paper Mario is known to not play well with other saves unless it's the same region.

Also on top of that, save states are more worse I believe since it requires the same Project64 version and a bunch of other stuff to match, plugins and what not (I could be wrong)

If you have a chance, use [this](https://uptobox.com/hw1lkk6f546z) it's from @Jj0YzL5nvJ from the [WIP Builds issue](https://github.com/ata4/angrylion-rdp-plus/issues/29)

It's angrylion's RDP Plus r7-116 and the latest build.

**Comment by zenseii** [comment] 2019-06-05 10:56
Okay, that works. I can also make a quick run on a pal version of the game
to get to the point since I've been playing it quite a lot recently. I'll
send the .sra as well since there is a save point right next to this. I
made the save with Pj64 2.3.

**Comment by RokkumanX** [comment] 2019-06-05 20:36
Thank you very much you absolute legend! I'll look forward to test this out!

**Comment by zenseii** [comment] 2019-06-05 21:43
Here's the .fla. Just walk all the way to the left by jumping on the platforms and you'll get to the second room on your left from the station.
Apparently (E) and (U) use the same save file since when I started up the (E) I got my save.

Also I tried downloading the latest WIP but I keep getting told that it contains a trojan...
[PAPER MARIO.zip](https://github.com/ata4/angrylion-rdp-plus/files/3259166/PAPER.MARIO.zip)

**Comment by RokkumanX** [comment] 2019-06-06 03:26
Thanks a lot, will test this as soon as I get home from work today.

Also here's a "Trojan" free alternative:
http://www.emutalk.net/threads/56728-Spread-the-word-angrylion-rdp-plus?p=465138&viewfull=1#post465138

**Comment by Jj0YzL5nvJ** [comment] 2019-06-06 09:35
If anyone knows a "safer" free-file-server for users without proper content filters and does not require an account. I'm all ears.

**Comment by RokkumanX** [comment] 2019-06-06 09:43
There is no Trojans in your packages, it has to be false positives.
I have downloaded your packages and they have been clean.

Keep using the same @Jj0YzL5nvJ 

Don't worry about it!

**Comment by Jj0YzL5nvJ** [comment] 2019-06-06 10:24
I know, I'm very paranoid and careful in that aspect.
But the advertising can potential redirect to content of dubious origin.

**Comment by RokkumanX** [comment] 2019-06-06 14:41
The issue is indeed present:

![paper](https://user-images.githubusercontent.com/50436544/59041759-8bd62b80-8879-11e9-940c-678ee7d72d66.png)

**angrylion's RDP Plus r7-116
Azimer's Audio v0.70 WIP 9
N-Rage Input Plugin V2 2.3c
RSP Plugin 1.7.4.958-g7a964b0**

Project64 2.4.0.958-g7a964b0 as seen in the screenshot.

**Comment by Jj0YzL5nvJ** [comment] 2019-06-06 18:15
**Firefox** with _**uMatrix**_ + **Peerguardian Linux** here.
<details>
  <summary>／人◕ ‿‿ ◕人＼</summary>
  <img src="https://i.imgur.com/88n5qJr.png" alt="" class="">
</details>

In fact, you only need CSS to get `uptobox.com` working almost like premium...

BTW, in most cases the save states of PJ64 are valid for mupen64plus too, but not vice versa.

**Comment by RokkumanX** [comment] 2019-06-07 14:59
I have tested this with these versions of the plugin so far:
1. angrylion's RDP Plus r7-82 (2018-11 something)
2. angrylion's RDP Plus r7-104 (2019-05-23)
3. angrylion's RDP Plus r7-116 (latest)

And it's the same result as above, and I also tried it out with Filtered + Nearest-Neighbor and Linear & Unfiltered + Nearest-Neighbor and Linear, same result.

Just for fun I decided to test it with GLideN64 Public Release 4.0 and as you can see it's similar

![paper2](https://user-images.githubusercontent.com/50436544/59113460-54cd4c00-8945-11e9-9167-d3e7bbbdcb54.png)

Either plugins seems to like darkness in Paper Mario. It's going to take some time figure out which build that broke this unless it's always been like this?

**Comment by RokkumanX** [comment] 2019-06-07 15:15
Made a quick test with angrylion's RDP Plus r4-68 (2017-10-18) and angrylion's RDP Plus r6-94 (2018-01-10) and it's the same issue as above.

These builds were taken from the WIP Builds thread and if even r4 builds is experiencing this then I don't know at all when this started.

I began to use this plugin around 2017 and still haven't played this game with this plugin as of today but it seems this issue have been around for quite some time.

**Comment by Jj0YzL5nvJ** [comment] 2019-06-07 22:42
This issue is similar to #74, it "fixes" by disabling `'Multithreaded rendering / Parallel'`.

> Just for fun I decided to test it with GLideN64 Public Release 4.0 and as you can see it's similar

GLideN64 4.0 works fine here:
http://0x0.st/zuMQ.png
http://0x0.st/zuM1.png

Try deleting your "Plugin\GFX\shaders" folder or by disabling "Store compiled shaders for performance".

**Comment by RokkumanX** [comment] 2019-06-08 04:56
No I'm not interested in GLideN64 enough to bother try fix the issue, I used most of the "Accuracy" settings anyway and that's how it looked.

As for this issue it was indeed fixed by disabling Multithreaded rendering, perfect lightning!
Performance didn't decrease at all, full speed without this option, amazing.

You solved the puzzle and now we know what is causing this issue in angrylion's RDP Plus, the one option I couldn't dream of to disable.

**Comment by ata4** [comment] 2019-06-10 11:40
I did some tests and it looks like it's another game where the threads need to be synchronized on ``Set_Texture_Image`` in order to fix issues. Since this reduces the multithreading performance gain a bit, I'm thinking about adding compatibility profiles so you can choose between compatibility and performance.

**Comment by RokkumanX** [comment] 2019-06-10 16:52
I agree, that seems to be the best course of action actually because I did some tests with multi-threading off in other games and even with my i7 8700K build I got severe slowdowns.

I do not recommend multi-threading off all the time. You can however choose freely once the game started whether to use multi-threading on/off without restarting.

But compatibility and performance profiles sound like an excellent idea.

**Comment by ata4** [comment] 2019-06-10 19:07
Okay, I have implemented that profile selection option. You can find a test build [here](https://cdn.discordapp.com/attachments/280429494190473226/587714264148475904/angrylion-plus.dll). The scene in Paper Mario demonstrates the difference between the profiles quite well.

**Comment by RokkumanX** [comment] 2020-02-11 08:11
This issue is solved since long, no need to keep it open anymore.
Just set DpCompat to 2 and voila!

You rock @ata4 and thanks again @Jj0YzL5nvJ for your builds!

**Closed** 2020-12-24 18:39 UTC
Labels: bug
