### ISSUE TITLE
Donkey Kong 64

### ISSUE THREAD

**Issue by wally86** [ata4/angrylion-rdp-plus#91] opened 2019-10-24 16:48 UTC
Hello. tested r7 and r8 and sometimes get this weird affect. Any help please?

![DONKEY KONG 64_0001](https://user-images.githubusercontent.com/8765045/67507206-78770180-f65c-11e9-8e79-05f420b8cef4.jpg)

**Comment by CrashOveride95** [comment] 2019-10-24 16:59
Ah yes, the classic bone stretching bug

What emulator are you using

**Comment by wally86** [comment] 2019-10-24 17:04
Project64 2.3.2

Angrylion r7 or r8

rsp 1.7

SHUNYUAN'S HLE 1.8.2

N-rage input, raphnet n64 USB with original controller

Windows 7 pro 64 
Intel i5 3470 3.20 ghz
Gtx 750 to
8gb ram

**Comment by LegendOfDragoon** [comment] 2019-10-24 17:08
use project64 2.4

**Comment by wally86** [comment] 2019-10-24 17:49
recommended 2.4 version? i downloaded the newest nightly and banjo koozie didn't load.

**Comment by LegendOfDragoon** [comment] 2019-10-24 22:22
Sorry, I forgot that LLE is broken in nightly 2.4 builds for Banjo, DK64, and a few other games made by Rare. Currently there's no convenient solution, but maybe soon it will be fixed.

**Comment by wally86** [comment] 2019-10-24 23:02
I tested a whole bunch of versions. I had to go all the way back to 2.0.4-452 so every thing worked. Got to see if dk64 is fix in that version yet

**Comment by LegendOfDragoon** [comment] 2019-10-24 23:22
At the time of writing my previous post, I wasn't sure if the bone displacement fix occurred before or after the LLE regression for Rare games. I just now checked the history, so now I'm confident that the build you referenced should work fine, since the bone displacement fix did happen before the LLE regression.

**Closed** 2021-01-07 16:33 UTC
Labels: wontfix
