### ISSUE TITLE
Feature request - Dithering pattern

### ISSUE THREAD

**Issue by Krusher97** [ata4/angrylion-rdp-plus#24] opened 2017-09-30 20:36 UTC
![mischief](https://user-images.githubusercontent.com/25664221/31049240-c1f80082-a64c-11e7-9236-d2c15c81a848.png)
Is there any way to enable a dithering pattern? The picture above is from a speedrun youtube video. The one below is how it looks in m64p.
![mischief_makers-004](https://user-images.githubusercontent.com/25664221/31049254-10398b80-a64d-11e7-9c24-1a41200ebdd4.png)

**Comment by SigmaVirus** [comment] 2017-10-01 11:22
The m64p image looks similar to how the filtered output looks like in angrylion-rdp-plus, have you tried changing to unfiltered in the video settings in m64p?

This is how unfiltered looks like and it resembles the dithered picture above:
![](http://www.libretro.com/wp-content/uploads/2016/07/HSLhkA9.png)

**Comment by Krusher97** [comment] 2017-10-01 13:09
![mischief_makers-005](https://user-images.githubusercontent.com/25664221/31054780-cfc38c3c-a6d7-11e7-9dee-a05f08d2dd7b.png)

Unfiltered just removes the native bilinear filtering and makes the image off centered.

**Comment by ata4** [comment] 2017-10-01 14:06
"speedrun youtube video" is a bit vague. Is that from an emulator? If so, which one? Or is it even a hardware capture?

**Comment by Krusher97** [comment] 2017-10-01 14:07
Its from an SGDQ run. As far as I know they do not run emulators.

**Comment by SigmaVirus** [comment] 2017-10-01 16:59
@Krusher97

OK, it looks really good actually and if it's on the real console then it really should be included and implemented.

**Comment by ata4** [comment] 2017-10-03 17:26
Looking at angrylion's code, it appears that dithering has already been implemented, yet it doesn't show up. I'm wondering if the dithering is for something else or if it's simply broken right now...

**Comment by SigmaVirus** [comment] 2017-10-04 05:42
I'm guessing it's broken, and if it's already implemented I have a hard time thinking it's for something else.

Now that I think about it, that image I linked to above is actually from the ParaLLEl-N64 Libretro core with angrylion enabled and compared to this which is taken from angrylion-rdp-plus the quality is different and more blurry.

I don't know which of the angrylions is the more accurate or not?

![pic01](https://user-images.githubusercontent.com/14175085/31161393-ff2f0842-a8d6-11e7-80f4-b20700772512.png)

**Comment by Krusher97** [comment] 2017-10-04 06:16
ParaLLEl has a dithering pattern but it doesn't seem to be accurate. That and there are other minor issues not present in angrylion-rdp-plus but exist in ParaLLEl. Top is the one with Dtihering enabled while bottom has it disabled.
![mischief makers usa -171004-114106](https://user-images.githubusercontent.com/25664221/31162143-4852c37a-a8f9-11e7-9af8-bf142113d8bb.png)
![mischief makers usa -171004-114220](https://user-images.githubusercontent.com/25664221/31162146-4d9afef6-a8f9-11e7-93c4-0c96aeaa4e80.png)

**Comment by SigmaVirus** [comment] 2017-10-04 07:50
This is indeed a quite interesting topic, I'm really anxious to see what unfolds from all this because a real accurate and pixel perfect N64 graphics plugin is what the world needs after all these years.

The top image which is presumed to be captured from a N64 looks so damn crisp and clean.

I looked at the video you provided @Krusher97  and I can't imagine they used an emulator in that AGDQ run because they're basically sitting in front of an older tube TV but I'm not 100% sure.

**Comment by ata4** [comment] 2017-10-05 20:33
Looking at the code again, it seems that the dithering code in the video interface is actually designed to *undo* the dithering effect produced by the display processor in 16 bit modes. But even when all filtering is disabled, there isn't a visible dithering pattern in that screen of the game. It is visible in other games, so the display processor dithering is working as intended. Therefore, I'm not convinced that this pattern is actually produced by the N64 hardware.

**Comment by SigmaVirus** [comment] 2017-10-06 12:05
It's been almost 15 years since I last played on a real N64 hooked to a tube TV so I have a very vague memory of how things used to look.

I know for a fact though that Angrylion is the closest thing yet when it comes to recreate the experience I had back then and no other plugin have even been close.

However I can't recall that the image back then was this blurry:

**Angrylion-RDP-Plus**
![](https://user-images.githubusercontent.com/14175085/31161393-ff2f0842-a8d6-11e7-80f4-b20700772512.png)

This looks somehow more right to me:

**ParaLLEl-N64 with Angrylion**
![](https://camo.githubusercontent.com/e3a18b8c9c28a1786f1e1bb60f9ec57a4783f115/687474703a2f2f7777772e6c6962726574726f2e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031362f30372f48534c686b41392e706e67)

I would like to hear you're thoughts on this!

**Comment by ata4** [comment] 2017-10-06 17:14
Did you swap the screenshots? Because the bottom is the blurry one. It's also the "correct" one, since the blur is part of the N64's anti-aliasing feature. But you can change between filtered and unfiltered any time in the options according to your preferences.

**Comment by SigmaVirus** [comment] 2017-10-06 19:18
I haven't swapped screenshots actually, the bottom image is how it looks in ParaLLEl-N64 and as far as I know it doesn't have a core option for filtered or unfiltered in Libretro.

I don't know what ParaLLEl-N64 is doing different but it doesn't look as blurry as the image taken from Angrylion-RDP-Plus.

Anyway I'm not complaining because I will use this plugin either way but I'm confused on how the original looked back then.

**Comment by AJR1991** [comment] 2017-10-08 18:12
Working fine for me. Antialiasing appears around edges. 
![image](https://user-images.githubusercontent.com/9122610/31319409-3002886c-ac20-11e7-9aeb-a17df92f0aa1.png)

Your game in the first screen shot appears to be different for some reason from the regular OoT version (red sword button? White bordered hearts?). Make sure you've enabled the default rdp to be angry lion plus and the game setting does not use something else.

**Comment by SigmaVirus** [comment] 2017-10-08 19:39
@AJR1991 

You are plying in Filtered output mode where I am playing in Unfiltered output mode, that's a huge difference.
I could post an identical image if I wanted.

And the reason I have different colors on my buttons is because I'm playing the dumped ROM of The Legend of Zelda - Ocarina of Time - Master Quest (GameCube Edition) (Europe) from the bonus disc shipped along with The Legend of Zelda - The Wind Waker for GameCube ripped in Dolphin.

**Comment by ata4** [comment] 2017-10-09 23:38
I can't really replicate the screenshot above. When I try ParaLLEl-N64 with Angrylion, the output looks pretty much exactly the same as PJ64's Angrylion or my fork. Yet, in your screenshot, it appears to be smoother than usual but with stronger dithering. Are you sure that's not the Vulkan renderer or something?

**Comment by SigmaVirus** [comment] 2017-10-10 11:45
It appears you are spot on @ata4 it's Vulkan.

I mixed up everything, I feel so ashamed....

**Comment by Krusher97** [comment] 2017-10-13 04:49
I noticed a bizarre behavior in the plugin right now. A dithering pattern exists but it only appears during certain screens.
![mystical_ninja-001](https://user-images.githubusercontent.com/25664221/31530662-a8aa06e0-afff-11e7-9cb3-499d32a5aa39.png)
![mystical_ninja-002](https://user-images.githubusercontent.com/25664221/31530666-adddde34-afff-11e7-8667-9b377584ae72.png)
The screenshots are around two seconds apart. 
Here is a save state during the cutscene in Mupen64plus if you want to see for yourself [Mystical Ninja Starring Goemon (U) [!].zip](https://github.com/ata4/angrylion-rdp-plus/files/1381437/Mystical.Ninja.Starring.Goemon.U.zip)

**Comment by theboy181** [comment] 2017-10-13 05:04
RSP bug?  Try pj64 with Zilmar rsp in lle

**Comment by Krusher97** [comment] 2017-10-13 05:09
Any way to convert one's save states to another?

**Comment by SigmaVirus** [comment] 2017-10-23 20:10
@Krusher97 
Sorry for the late reply but in case you haven't noticed yet, save games (not save states) is interchangeable between Project64 and the m64p project so you could easily switch save files between the two emulators.

It's pretty damn handy!

**Comment by SigmaVirus** [comment] 2018-01-04 08:03
Coming back to this I feel like **Unfiltered + Linear** is giving me a really satisfying look

![](https://user-images.githubusercontent.com/14175085/34325408-ffad54dc-e890-11e7-9473-fdb7be4d2716.png)

It looks nearly as good as this image I posted originally

![](https://camo.githubusercontent.com/e3a18b8c9c28a1786f1e1bb60f9ec57a4783f115/687474703a2f2f7777772e6c6962726574726f2e636f6d2f77702d636f6e74656e742f75706c6f6164732f323031362f30372f48534c686b41392e706e67)

In my book things doesn't get much better than that!

**Comment by ata4** [comment] 2018-02-19 11:24
I'll close this, since linear filtering appears to produce the desired look.

**Closed by ata4** 2018-02-19 11:24 UTC
Labels: enhancement
