### ISSUE TITLE
"Please disable 'Graphic HLE' in the plugin settings" on latest Project64 development builds

### ISSUE THREAD

**Issue by DaRkL3AD3R** [ata4/angrylion-rdp-plus#79] opened 2018-12-25 15:21 UTC
Title. HLE is disabled for graphics. When executing a ROM, the first frame is visible but then it halts and spits out the quoted error above.

**Comment by DaRkL3AD3R** [comment] 2018-12-29 14:50
![broken lle](https://user-images.githubusercontent.com/29787293/50539478-03779000-0b4f-11e9-98fb-f6c5b86785db.jpg)

Yeah this started happening when I updated from an old 2.3.2 build of Project 64 to the recently unlocked development builds.

**Comment by theboy181** [comment] 2018-12-29 18:13
Uncheck HLE in the plugins option.

**Comment by DaRkL3AD3R** [comment] 2018-12-29 18:32
It is.  That's why the sudden issue. It's as if something changed in PJ64 in their dev builds that makes it so the plugin cannot see the true state of that option.

**Comment by theboy181** [comment] 2018-12-29 19:32
No its that you are using a plugin now that supports HLE and LLE. The other option would be to add CDX4's RSP and leave it in LLE mode. 

It would be good if LLE only plugins would use LLE mode by default. It is what it is.

**Comment by LegendOfDragoon** [comment] 2018-12-29 20:00
This is Project64's fault, not the graphics plugin. Now i can't use LLE, despite configuring the RSP for LLE.. Seems like this issue is mentioned here https://github.com/project64/project64/issues/1501

So this issue can be closed and hopefully someone fixes the regression in Project64.

**Comment by theboy181** [comment] 2018-12-29 20:14
WOW, I just tested this and I see now. How long has it been broken? and what PR?

**Comment by RokkumanX** [comment] 2019-05-27 06:58
This issue can now be closed as it's already stated that it's not the plugins fault and the mentioned problem with Project64 is solved since long.

There are no more issues here.

**Comment by ata4** [comment] 2019-05-27 15:43
Agreed, I just wasn't quite sure if it has been resolved in Project 64. But it sounds like it is.

**Closed by ata4** 2019-05-27 15:43 UTC
